kind: pipeline
name: node.v12
steps:
- name: node:test
  image: node:12
  commands:
  - sleep 15
  - npm install
  - npm run lint
  - npm run test:drone
  - npm run codecov:upload

services:
- name: drone.mariadb
  image: mariadb
  ports:
  - 3306
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: mysql

---
kind: pipeline
name: node.v10
steps:
- name: node:test
  image: node:10
  commands:
  - sleep 15
  - npm install
  - npm run lint
  - npm run test:drone
  - npm run codecov:upload

services:
- name: drone.mariadb
  image: mariadb
  ports:
  - 3306
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: mysql

---
kind: pipeline
name: node.v8
steps:
- name: node:test
  image: node:8
  commands:
  - sleep 15
  - npm install
  - npm run lint
  - npm run test:drone
  - npm run codecov:upload

services:
- name: drone.mariadb
  image: mariadb
  ports:
  - 3306
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: mysql
