name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Stop MySQL
      run: sudo systemctl stop mysql

    - name: Start MariaDB/MySQL server
      uses: mirromutth/mysql-action@v1
      with:
        mysql database: 'mysql'
        mysql user: 'root'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install & style lint & test
      run: |
        npm install
        npm run lint
        npm test
      env:
        CI: true

  coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
      - run: npm run codecov:upload
