name: test

on: 
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: 
          - 8
          - 10
          - 12

    steps:
    - name: Stop MySQL
      run: sudo systemctl stop mysql

    - name: Start MariaDB/MySQL server
      uses: getong/mariadb-action@v1.1
      with:
        mariadb version: 'latest'
        character set server: 'utf8mb4'
        collation server: 'utf8mb4_general_ci'
        mysql database: 'mysql'
      env:
        MYSQL_DATABASE: 'mysql'
        MYSQL_ALLOW_EMPTY_PASSWORD: true

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node }}
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Version
      run: npm version

    - name: Install
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Tests
      run: npm run test

  # coverage:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: codecov/codecov-action@v1.0.3
  #       with:
  #         token: ${{secrets.CODECOV_TOKEN}}
  #     - run: npm run codecov:upload
