name: test

on: 
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 10
          - 12
          - 14
        db: [
          'mariadb:latest'
        ]

    name: Node.js ${{ matrix.node-version }} - ${{ matrix.db }}

    steps:
      - name: Stop the Default MySQL
        run: sudo systemctl stop mysql

      - name: Start MariaDB/MySQL server
        uses: getong/mariadb-action@v1.1
        with:
          # mariadb version: 'latest'
          character set server: 'utf8mb4'
          collation server: 'utf8mb4_general_ci'
        env:
          MYSQL_DATABASE: 'mysql'
          MYSQL_ALLOW_EMPTY_PASSWORD: true

      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: |
          npm version
          npm install

      - name: Lint
        run: npm run lint

      - name: Tests
        run: npm run test

  # coverage:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: codecov/codecov-action@v1.0.3
  #       with:
  #         token: ${{secrets.CODECOV_TOKEN}}
  #     - run: npm run codecov:upload
